sudo: required

services:
  - docker
script:
  - echo "Hello Students!"


after_success : 

  - docker build -t chinmayaramana/zomato-master-client ./client
  - docker build -t chinmayaramana/zomato-master-server ./server
  - docker build -t chinmayaramana/zomato-master-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push chinmayaramana/zomato-master-client
  - docker push chinmayaramana/zomato-master-server
  - docker push chinmayaramana/zomato-master-nginx

deploy : 

  provider : elasticbeanstalk
  region : ap-south-1
  app: zomato-master
  env: Zomatomaster-env
  bucket_name: elasticbeanstalk-us-east-2-826385745603
  bucket_path: zomato-clone
  on:
    branch: master
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET

